apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scrapyd-k8s-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scrapyd-k8s
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
